SELECT * FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES;

-- SINGLE LINE COMMENT

/*
    MULTI LINE COMMENT
 */

-- GET ME FIRSTNAME FROM EMPLOYEES
SELECT FIRST_NAME FROM EMPLOYEES;

-- GET ME FIRSTNAME AND SALARY FROM EMPLOYEES
SELECT FIRST_NAME,SALARY FROM EMPLOYEES;

-- GET ME FIRSTNAME, LAST NAME AND SALARY FROM EMPLOYEES
SELECT FIRST_NAME,LAST NAME, SALARY FROM EMPLOYEES;

--display all information from employees table.
SELECT * FROM EMPLOYEES;

--display all information from departments table.
SELECT * FROM DEPARTMENTS;

--display all information from locations table
SELECT * FROM LOCATIONS;

--display all information from COUNTRIES table
SELECT * FROM COUNTRIES;

--display all information from JOBS table
SELECT * FROM JOBS;

--display street and postal cods from locations table
SELECT STREET_ADDRESS, POSTAL_CODE FROM LOCATIONS;

--display DEPARTMENT NAMES  from departments table.
SELECT DEPARTMENT_NAME FROM DEPARTMENTS;

--display region name from regions table
SELECT REGION_NAME FROM REGIONS;

SELECT FIRST_NAME, DEPARTMENT_NAME FROM EMPLOYEES,DEPARTMENTS;


