SELECT *
FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES;

SELECT COUNT(*)
FROM EMPLOYEES
where SALARY < 5000;

SELECT count(*)
from EMPLOYEES
WHERE SALARY between 6000 AND 7000;

SELECT DISTINCT region_id
FROM countries;

SELECT SALARY
FROM EMPLOYEES
WHERE LAST_NAME = 'Grant'
  AND FIRST_NAME = 'Douglas';

SELECT *
from DEPARTMENTS
where DEPARTMENT_NAME in ('IT', 'Public Relations', 'Sales', 'Executive');

select MAX(SALARY)
from EMPLOYEES;

select Min(SALARY)
from EMPLOYEES;

select avg(SALARY)
from EMPLOYEES;

SELECT COUNT(*) AS TOTALDEPARTMENTS
FROM DEPARTMENTS;

SELECT *
FROM job_history
ORDER BY start_date ASC;

SELECT *
FROM job_history
ORDER BY start_date DESC;

SELECT *
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%a%a%';

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%';

SELECT *
FROM EMPLOYEES
WHERE JOB_ID LIKE '%IT%';

SELECT *
FROM EMPLOYEES
WHERE JOB_ID LIKE '%CLERC';

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A____';

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (50, 80, 100);

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID NOT IN (90, 60, 100, 130, 120);

SELECT JOB_ID, MAX(salary) AS max_salary
FROM employees
GROUP BY JOB_ID;

SELECT JOB_ID, MIN(salary) AS MIN_salary
FROM employees
GROUP BY JOB_ID;

SELECT JOB_ID, AVG(salary) AS AVG_salary
FROM employees
GROUP BY JOB_ID;

SELECT JOB_ID, COUNT(*) AS EMPLOYES
FROM EMPLOYEES
where SALARY >= 5000
GROUP BY JOB_ID;

SELECT JOB_ID, SUM(salary) AS total_budget
FROM employees
GROUP BY JOB_ID;

-- 21. display all job_id and average .....ERROR

SELECT DEPARTMENT_ID, MAX(salary) AS max_salary
FROM employees
GROUP BY DEPARTMENT_ID;

SELECT department_id, SUM(salary) AS total_salary
FROM employees
WHERE department_id != 50
GROUP BY department_id
HAVING SUM(salary) > 30000;

